/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}', './docs/**/*.html'],
  theme: {
    extend: {
      colors: {
        'on-surface-variant': '#566166',
        'inverse-on-surface': '#9a9d9f',
        'on-tertiary-fixed-variant': '#54546f',
        'tertiary-container': '#d9d7f8',
        'on-tertiary': '#fbf7ff',
        'on-secondary-fixed-variant': '#4e5c71',
        outline: '#717c82',
        secondary: '#526074',
        'on-secondary-fixed': '#324053',
        'secondary-dim': '#465468',
        'error-container': '#fe8983',
        primary: '#455f88',
        'primary-fixed': '#d6e3ff',
        'on-secondary': '#f8f8ff',
        background: '#f7f9fb',
        'on-primary-fixed': '#254067',
        'surface-container-lowest': '#ffffff',
        'secondary-fixed': '#d5e3fc',
        'surface-container-high': '#e1e9ee',
        'on-background': '#2a3439',
        'on-error-container': '#752121',
        'inverse-surface': '#0b0f10',
        'surface-container-highest': '#d9e4ea',
        'secondary-container': '#d5e3fc',
        'surface-container-low': '#f0f4f7',
        'on-primary-fixed-variant': '#425c85',
        'tertiary-fixed': '#d9d7f8',
        'on-secondary-container': '#455367',
        'on-primary': '#f6f7ff',
        tertiary: '#5d5d78',
        'tertiary-dim': '#51516c',
        'surface-dim': '#cfdce3',
        'outline-variant': '#a9b4b9',
        'on-error': '#fff7f6',
        'error-dim': '#4e0309',
        'surface-variant': '#d9e4ea',
        'secondary-fixed-dim': '#c7d5ed',
        'surface-container': '#e8eff3',
        'surface-bright': '#f7f9fb',
        error: '#9f403d',
        'primary-dim': '#39537c',
        'surface-tint': '#455f88',
        surface: '#f7f9fb',
        'on-primary-container': '#38527b',
        'primary-container': '#d6e3ff',
        'primary-fixed-dim': '#bfd5ff',
        'on-tertiary-fixed': '#373851',
        'tertiary-fixed-dim': '#cbc9e9',
        'inverse-primary': '#b3cdfd',
        'on-surface': '#2a3439',
        'on-tertiary-container': '#4a4a65',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
